//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoomagazin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies
    {
        public int Id_Supplies { get; set; }
        public Nullable<int> id_poctav { get; set; }
        public Nullable<int> id_tt { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public byte[] Exel { get; set; }
    
        public virtual SalesPoints SalesPoints { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
