//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoomagazin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int ID { get; set; }
        public string Название { get; set; }
        public Nullable<int> id_категории { get; set; }
        public string описание { get; set; }
        public Nullable<decimal> цена { get; set; }
        public string Кол_воТовара { get; set; }
        public Nullable<int> id_SalesPoints { get; set; }
    
        public virtual Kat_Tovar Kat_Tovar { get; set; }
        public virtual SalesPoints SalesPoints { get; set; }
    }
}
