//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoomagazin
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSchedule
    {
        public int id { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> SalesPointID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual SalesPoints SalesPoints { get; set; }
    }
}
